version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Downloading Terraform..."
      - rm -rf terraform terraform.zip
      - curl -s -o terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip -o terraform.zip                   
      - mv terraform /usr/local/bin/
      - terraform version

      - echo "Downloading Terraform..."
      - rm -rf terraform terraform.zip
      - curl -s -o terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip -o terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version

  build:
    commands:
      - cd cloud_infra
      - terraform init -backend-config=backend-config.hcl
      - terraform workspace select dev || terraform workspace new dev
      - terraform plan
      - terraform apply -auto-approve -lock=true
