name: CI

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init -backend-config=backend-config.hcl
      - name: select workspace
        run: terraform workspace select dev || terraform workspace new dev
        working-directory: ./terraform
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform
